// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/distance.proto

package com.example.demo.protobuf;

public interface AddressDetailsPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.AddressDetailsP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 3;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 3;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string country = 4;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 4;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string latitude = 5;</code>
   * @return The latitude.
   */
  java.lang.String getLatitude();
  /**
   * <code>string latitude = 5;</code>
   * @return The bytes for latitude.
   */
  com.google.protobuf.ByteString
      getLatitudeBytes();

  /**
   * <code>string longitude = 6;</code>
   * @return The longitude.
   */
  java.lang.String getLongitude();
  /**
   * <code>string longitude = 6;</code>
   * @return The bytes for longitude.
   */
  com.google.protobuf.ByteString
      getLongitudeBytes();
}
