// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/distance.proto

package com.example.demo.protobuf;

/**
 * Protobuf type {@code proto.DistanceP}
 */
public final class DistanceP extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.DistanceP)
    DistancePOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DistanceP.newBuilder() to construct.
  private DistanceP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DistanceP() {
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DistanceP();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DistanceP(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            com.example.demo.protobuf.AddressDetailsP.Builder subBuilder = null;
            if (originAddress_ != null) {
              subBuilder = originAddress_.toBuilder();
            }
            originAddress_ = input.readMessage(com.example.demo.protobuf.AddressDetailsP.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(originAddress_);
              originAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.example.demo.protobuf.AddressDetailsP.Builder subBuilder = null;
            if (destinationAddress_ != null) {
              subBuilder = destinationAddress_.toBuilder();
            }
            destinationAddress_ = input.readMessage(com.example.demo.protobuf.AddressDetailsP.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(destinationAddress_);
              destinationAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            distanceInKm_ = input.readInt32();
            break;
          }
          case 40: {

            transitTimeHours_ = input.readInt32();
            break;
          }
          case 50: {
            com.example.demo.protobuf.Dummy1P.Builder subBuilder = null;
            if (dummy1_ != null) {
              subBuilder = dummy1_.toBuilder();
            }
            dummy1_ = input.readMessage(com.example.demo.protobuf.Dummy1P.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dummy1_);
              dummy1_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.example.demo.protobuf.Dummy2P.Builder subBuilder = null;
            if (dummy2_ != null) {
              subBuilder = dummy2_.toBuilder();
            }
            dummy2_ = input.readMessage(com.example.demo.protobuf.Dummy2P.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dummy2_);
              dummy2_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.protobuf.DistanceProto.internal_static_proto_DistanceP_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.protobuf.DistanceProto.internal_static_proto_DistanceP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.protobuf.DistanceP.class, com.example.demo.protobuf.DistanceP.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGIN_ADDRESS_FIELD_NUMBER = 2;
  private com.example.demo.protobuf.AddressDetailsP originAddress_;
  /**
   * <code>.proto.AddressDetailsP origin_address = 2;</code>
   * @return Whether the originAddress field is set.
   */
  @java.lang.Override
  public boolean hasOriginAddress() {
    return originAddress_ != null;
  }
  /**
   * <code>.proto.AddressDetailsP origin_address = 2;</code>
   * @return The originAddress.
   */
  @java.lang.Override
  public com.example.demo.protobuf.AddressDetailsP getOriginAddress() {
    return originAddress_ == null ? com.example.demo.protobuf.AddressDetailsP.getDefaultInstance() : originAddress_;
  }
  /**
   * <code>.proto.AddressDetailsP origin_address = 2;</code>
   */
  @java.lang.Override
  public com.example.demo.protobuf.AddressDetailsPOrBuilder getOriginAddressOrBuilder() {
    return getOriginAddress();
  }

  public static final int DESTINATION_ADDRESS_FIELD_NUMBER = 3;
  private com.example.demo.protobuf.AddressDetailsP destinationAddress_;
  /**
   * <code>.proto.AddressDetailsP destination_address = 3;</code>
   * @return Whether the destinationAddress field is set.
   */
  @java.lang.Override
  public boolean hasDestinationAddress() {
    return destinationAddress_ != null;
  }
  /**
   * <code>.proto.AddressDetailsP destination_address = 3;</code>
   * @return The destinationAddress.
   */
  @java.lang.Override
  public com.example.demo.protobuf.AddressDetailsP getDestinationAddress() {
    return destinationAddress_ == null ? com.example.demo.protobuf.AddressDetailsP.getDefaultInstance() : destinationAddress_;
  }
  /**
   * <code>.proto.AddressDetailsP destination_address = 3;</code>
   */
  @java.lang.Override
  public com.example.demo.protobuf.AddressDetailsPOrBuilder getDestinationAddressOrBuilder() {
    return getDestinationAddress();
  }

  public static final int DISTANCE_IN_KM_FIELD_NUMBER = 4;
  private int distanceInKm_;
  /**
   * <code>int32 distance_in_km = 4;</code>
   * @return The distanceInKm.
   */
  @java.lang.Override
  public int getDistanceInKm() {
    return distanceInKm_;
  }

  public static final int TRANSIT_TIME_HOURS_FIELD_NUMBER = 5;
  private int transitTimeHours_;
  /**
   * <code>int32 transit_time_hours = 5;</code>
   * @return The transitTimeHours.
   */
  @java.lang.Override
  public int getTransitTimeHours() {
    return transitTimeHours_;
  }

  public static final int DUMMY1_FIELD_NUMBER = 6;
  private com.example.demo.protobuf.Dummy1P dummy1_;
  /**
   * <code>.proto.Dummy1P dummy1 = 6;</code>
   * @return Whether the dummy1 field is set.
   */
  @java.lang.Override
  public boolean hasDummy1() {
    return dummy1_ != null;
  }
  /**
   * <code>.proto.Dummy1P dummy1 = 6;</code>
   * @return The dummy1.
   */
  @java.lang.Override
  public com.example.demo.protobuf.Dummy1P getDummy1() {
    return dummy1_ == null ? com.example.demo.protobuf.Dummy1P.getDefaultInstance() : dummy1_;
  }
  /**
   * <code>.proto.Dummy1P dummy1 = 6;</code>
   */
  @java.lang.Override
  public com.example.demo.protobuf.Dummy1POrBuilder getDummy1OrBuilder() {
    return getDummy1();
  }

  public static final int DUMMY2_FIELD_NUMBER = 7;
  private com.example.demo.protobuf.Dummy2P dummy2_;
  /**
   * <code>.proto.Dummy2P dummy2 = 7;</code>
   * @return Whether the dummy2 field is set.
   */
  @java.lang.Override
  public boolean hasDummy2() {
    return dummy2_ != null;
  }
  /**
   * <code>.proto.Dummy2P dummy2 = 7;</code>
   * @return The dummy2.
   */
  @java.lang.Override
  public com.example.demo.protobuf.Dummy2P getDummy2() {
    return dummy2_ == null ? com.example.demo.protobuf.Dummy2P.getDefaultInstance() : dummy2_;
  }
  /**
   * <code>.proto.Dummy2P dummy2 = 7;</code>
   */
  @java.lang.Override
  public com.example.demo.protobuf.Dummy2POrBuilder getDummy2OrBuilder() {
    return getDummy2();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (originAddress_ != null) {
      output.writeMessage(2, getOriginAddress());
    }
    if (destinationAddress_ != null) {
      output.writeMessage(3, getDestinationAddress());
    }
    if (distanceInKm_ != 0) {
      output.writeInt32(4, distanceInKm_);
    }
    if (transitTimeHours_ != 0) {
      output.writeInt32(5, transitTimeHours_);
    }
    if (dummy1_ != null) {
      output.writeMessage(6, getDummy1());
    }
    if (dummy2_ != null) {
      output.writeMessage(7, getDummy2());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (originAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOriginAddress());
    }
    if (destinationAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDestinationAddress());
    }
    if (distanceInKm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, distanceInKm_);
    }
    if (transitTimeHours_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, transitTimeHours_);
    }
    if (dummy1_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDummy1());
    }
    if (dummy2_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDummy2());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.protobuf.DistanceP)) {
      return super.equals(obj);
    }
    com.example.demo.protobuf.DistanceP other = (com.example.demo.protobuf.DistanceP) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasOriginAddress() != other.hasOriginAddress()) return false;
    if (hasOriginAddress()) {
      if (!getOriginAddress()
          .equals(other.getOriginAddress())) return false;
    }
    if (hasDestinationAddress() != other.hasDestinationAddress()) return false;
    if (hasDestinationAddress()) {
      if (!getDestinationAddress()
          .equals(other.getDestinationAddress())) return false;
    }
    if (getDistanceInKm()
        != other.getDistanceInKm()) return false;
    if (getTransitTimeHours()
        != other.getTransitTimeHours()) return false;
    if (hasDummy1() != other.hasDummy1()) return false;
    if (hasDummy1()) {
      if (!getDummy1()
          .equals(other.getDummy1())) return false;
    }
    if (hasDummy2() != other.hasDummy2()) return false;
    if (hasDummy2()) {
      if (!getDummy2()
          .equals(other.getDummy2())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasOriginAddress()) {
      hash = (37 * hash) + ORIGIN_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getOriginAddress().hashCode();
    }
    if (hasDestinationAddress()) {
      hash = (37 * hash) + DESTINATION_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationAddress().hashCode();
    }
    hash = (37 * hash) + DISTANCE_IN_KM_FIELD_NUMBER;
    hash = (53 * hash) + getDistanceInKm();
    hash = (37 * hash) + TRANSIT_TIME_HOURS_FIELD_NUMBER;
    hash = (53 * hash) + getTransitTimeHours();
    if (hasDummy1()) {
      hash = (37 * hash) + DUMMY1_FIELD_NUMBER;
      hash = (53 * hash) + getDummy1().hashCode();
    }
    if (hasDummy2()) {
      hash = (37 * hash) + DUMMY2_FIELD_NUMBER;
      hash = (53 * hash) + getDummy2().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.protobuf.DistanceP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protobuf.DistanceP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.demo.protobuf.DistanceP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protobuf.DistanceP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.protobuf.DistanceP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.DistanceP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.DistanceP)
      com.example.demo.protobuf.DistancePOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protobuf.DistanceProto.internal_static_proto_DistanceP_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protobuf.DistanceProto.internal_static_proto_DistanceP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protobuf.DistanceP.class, com.example.demo.protobuf.DistanceP.Builder.class);
    }

    // Construct using com.example.demo.protobuf.DistanceP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (originAddressBuilder_ == null) {
        originAddress_ = null;
      } else {
        originAddress_ = null;
        originAddressBuilder_ = null;
      }
      if (destinationAddressBuilder_ == null) {
        destinationAddress_ = null;
      } else {
        destinationAddress_ = null;
        destinationAddressBuilder_ = null;
      }
      distanceInKm_ = 0;

      transitTimeHours_ = 0;

      if (dummy1Builder_ == null) {
        dummy1_ = null;
      } else {
        dummy1_ = null;
        dummy1Builder_ = null;
      }
      if (dummy2Builder_ == null) {
        dummy2_ = null;
      } else {
        dummy2_ = null;
        dummy2Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.protobuf.DistanceProto.internal_static_proto_DistanceP_descriptor;
    }

    @java.lang.Override
    public com.example.demo.protobuf.DistanceP getDefaultInstanceForType() {
      return com.example.demo.protobuf.DistanceP.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.protobuf.DistanceP build() {
      com.example.demo.protobuf.DistanceP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.protobuf.DistanceP buildPartial() {
      com.example.demo.protobuf.DistanceP result = new com.example.demo.protobuf.DistanceP(this);
      result.id_ = id_;
      if (originAddressBuilder_ == null) {
        result.originAddress_ = originAddress_;
      } else {
        result.originAddress_ = originAddressBuilder_.build();
      }
      if (destinationAddressBuilder_ == null) {
        result.destinationAddress_ = destinationAddress_;
      } else {
        result.destinationAddress_ = destinationAddressBuilder_.build();
      }
      result.distanceInKm_ = distanceInKm_;
      result.transitTimeHours_ = transitTimeHours_;
      if (dummy1Builder_ == null) {
        result.dummy1_ = dummy1_;
      } else {
        result.dummy1_ = dummy1Builder_.build();
      }
      if (dummy2Builder_ == null) {
        result.dummy2_ = dummy2_;
      } else {
        result.dummy2_ = dummy2Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.protobuf.DistanceP) {
        return mergeFrom((com.example.demo.protobuf.DistanceP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.protobuf.DistanceP other) {
      if (other == com.example.demo.protobuf.DistanceP.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasOriginAddress()) {
        mergeOriginAddress(other.getOriginAddress());
      }
      if (other.hasDestinationAddress()) {
        mergeDestinationAddress(other.getDestinationAddress());
      }
      if (other.getDistanceInKm() != 0) {
        setDistanceInKm(other.getDistanceInKm());
      }
      if (other.getTransitTimeHours() != 0) {
        setTransitTimeHours(other.getTransitTimeHours());
      }
      if (other.hasDummy1()) {
        mergeDummy1(other.getDummy1());
      }
      if (other.hasDummy2()) {
        mergeDummy2(other.getDummy2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.demo.protobuf.DistanceP parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.demo.protobuf.DistanceP) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.example.demo.protobuf.AddressDetailsP originAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.AddressDetailsP, com.example.demo.protobuf.AddressDetailsP.Builder, com.example.demo.protobuf.AddressDetailsPOrBuilder> originAddressBuilder_;
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     * @return Whether the originAddress field is set.
     */
    public boolean hasOriginAddress() {
      return originAddressBuilder_ != null || originAddress_ != null;
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     * @return The originAddress.
     */
    public com.example.demo.protobuf.AddressDetailsP getOriginAddress() {
      if (originAddressBuilder_ == null) {
        return originAddress_ == null ? com.example.demo.protobuf.AddressDetailsP.getDefaultInstance() : originAddress_;
      } else {
        return originAddressBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    public Builder setOriginAddress(com.example.demo.protobuf.AddressDetailsP value) {
      if (originAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        originAddress_ = value;
        onChanged();
      } else {
        originAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    public Builder setOriginAddress(
        com.example.demo.protobuf.AddressDetailsP.Builder builderForValue) {
      if (originAddressBuilder_ == null) {
        originAddress_ = builderForValue.build();
        onChanged();
      } else {
        originAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    public Builder mergeOriginAddress(com.example.demo.protobuf.AddressDetailsP value) {
      if (originAddressBuilder_ == null) {
        if (originAddress_ != null) {
          originAddress_ =
            com.example.demo.protobuf.AddressDetailsP.newBuilder(originAddress_).mergeFrom(value).buildPartial();
        } else {
          originAddress_ = value;
        }
        onChanged();
      } else {
        originAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    public Builder clearOriginAddress() {
      if (originAddressBuilder_ == null) {
        originAddress_ = null;
        onChanged();
      } else {
        originAddress_ = null;
        originAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    public com.example.demo.protobuf.AddressDetailsP.Builder getOriginAddressBuilder() {
      
      onChanged();
      return getOriginAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    public com.example.demo.protobuf.AddressDetailsPOrBuilder getOriginAddressOrBuilder() {
      if (originAddressBuilder_ != null) {
        return originAddressBuilder_.getMessageOrBuilder();
      } else {
        return originAddress_ == null ?
            com.example.demo.protobuf.AddressDetailsP.getDefaultInstance() : originAddress_;
      }
    }
    /**
     * <code>.proto.AddressDetailsP origin_address = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.AddressDetailsP, com.example.demo.protobuf.AddressDetailsP.Builder, com.example.demo.protobuf.AddressDetailsPOrBuilder> 
        getOriginAddressFieldBuilder() {
      if (originAddressBuilder_ == null) {
        originAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.demo.protobuf.AddressDetailsP, com.example.demo.protobuf.AddressDetailsP.Builder, com.example.demo.protobuf.AddressDetailsPOrBuilder>(
                getOriginAddress(),
                getParentForChildren(),
                isClean());
        originAddress_ = null;
      }
      return originAddressBuilder_;
    }

    private com.example.demo.protobuf.AddressDetailsP destinationAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.AddressDetailsP, com.example.demo.protobuf.AddressDetailsP.Builder, com.example.demo.protobuf.AddressDetailsPOrBuilder> destinationAddressBuilder_;
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     * @return Whether the destinationAddress field is set.
     */
    public boolean hasDestinationAddress() {
      return destinationAddressBuilder_ != null || destinationAddress_ != null;
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     * @return The destinationAddress.
     */
    public com.example.demo.protobuf.AddressDetailsP getDestinationAddress() {
      if (destinationAddressBuilder_ == null) {
        return destinationAddress_ == null ? com.example.demo.protobuf.AddressDetailsP.getDefaultInstance() : destinationAddress_;
      } else {
        return destinationAddressBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    public Builder setDestinationAddress(com.example.demo.protobuf.AddressDetailsP value) {
      if (destinationAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destinationAddress_ = value;
        onChanged();
      } else {
        destinationAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    public Builder setDestinationAddress(
        com.example.demo.protobuf.AddressDetailsP.Builder builderForValue) {
      if (destinationAddressBuilder_ == null) {
        destinationAddress_ = builderForValue.build();
        onChanged();
      } else {
        destinationAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    public Builder mergeDestinationAddress(com.example.demo.protobuf.AddressDetailsP value) {
      if (destinationAddressBuilder_ == null) {
        if (destinationAddress_ != null) {
          destinationAddress_ =
            com.example.demo.protobuf.AddressDetailsP.newBuilder(destinationAddress_).mergeFrom(value).buildPartial();
        } else {
          destinationAddress_ = value;
        }
        onChanged();
      } else {
        destinationAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    public Builder clearDestinationAddress() {
      if (destinationAddressBuilder_ == null) {
        destinationAddress_ = null;
        onChanged();
      } else {
        destinationAddress_ = null;
        destinationAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    public com.example.demo.protobuf.AddressDetailsP.Builder getDestinationAddressBuilder() {
      
      onChanged();
      return getDestinationAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    public com.example.demo.protobuf.AddressDetailsPOrBuilder getDestinationAddressOrBuilder() {
      if (destinationAddressBuilder_ != null) {
        return destinationAddressBuilder_.getMessageOrBuilder();
      } else {
        return destinationAddress_ == null ?
            com.example.demo.protobuf.AddressDetailsP.getDefaultInstance() : destinationAddress_;
      }
    }
    /**
     * <code>.proto.AddressDetailsP destination_address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.AddressDetailsP, com.example.demo.protobuf.AddressDetailsP.Builder, com.example.demo.protobuf.AddressDetailsPOrBuilder> 
        getDestinationAddressFieldBuilder() {
      if (destinationAddressBuilder_ == null) {
        destinationAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.demo.protobuf.AddressDetailsP, com.example.demo.protobuf.AddressDetailsP.Builder, com.example.demo.protobuf.AddressDetailsPOrBuilder>(
                getDestinationAddress(),
                getParentForChildren(),
                isClean());
        destinationAddress_ = null;
      }
      return destinationAddressBuilder_;
    }

    private int distanceInKm_ ;
    /**
     * <code>int32 distance_in_km = 4;</code>
     * @return The distanceInKm.
     */
    @java.lang.Override
    public int getDistanceInKm() {
      return distanceInKm_;
    }
    /**
     * <code>int32 distance_in_km = 4;</code>
     * @param value The distanceInKm to set.
     * @return This builder for chaining.
     */
    public Builder setDistanceInKm(int value) {
      
      distanceInKm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 distance_in_km = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistanceInKm() {
      
      distanceInKm_ = 0;
      onChanged();
      return this;
    }

    private int transitTimeHours_ ;
    /**
     * <code>int32 transit_time_hours = 5;</code>
     * @return The transitTimeHours.
     */
    @java.lang.Override
    public int getTransitTimeHours() {
      return transitTimeHours_;
    }
    /**
     * <code>int32 transit_time_hours = 5;</code>
     * @param value The transitTimeHours to set.
     * @return This builder for chaining.
     */
    public Builder setTransitTimeHours(int value) {
      
      transitTimeHours_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transit_time_hours = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransitTimeHours() {
      
      transitTimeHours_ = 0;
      onChanged();
      return this;
    }

    private com.example.demo.protobuf.Dummy1P dummy1_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.Dummy1P, com.example.demo.protobuf.Dummy1P.Builder, com.example.demo.protobuf.Dummy1POrBuilder> dummy1Builder_;
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     * @return Whether the dummy1 field is set.
     */
    public boolean hasDummy1() {
      return dummy1Builder_ != null || dummy1_ != null;
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     * @return The dummy1.
     */
    public com.example.demo.protobuf.Dummy1P getDummy1() {
      if (dummy1Builder_ == null) {
        return dummy1_ == null ? com.example.demo.protobuf.Dummy1P.getDefaultInstance() : dummy1_;
      } else {
        return dummy1Builder_.getMessage();
      }
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    public Builder setDummy1(com.example.demo.protobuf.Dummy1P value) {
      if (dummy1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dummy1_ = value;
        onChanged();
      } else {
        dummy1Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    public Builder setDummy1(
        com.example.demo.protobuf.Dummy1P.Builder builderForValue) {
      if (dummy1Builder_ == null) {
        dummy1_ = builderForValue.build();
        onChanged();
      } else {
        dummy1Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    public Builder mergeDummy1(com.example.demo.protobuf.Dummy1P value) {
      if (dummy1Builder_ == null) {
        if (dummy1_ != null) {
          dummy1_ =
            com.example.demo.protobuf.Dummy1P.newBuilder(dummy1_).mergeFrom(value).buildPartial();
        } else {
          dummy1_ = value;
        }
        onChanged();
      } else {
        dummy1Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    public Builder clearDummy1() {
      if (dummy1Builder_ == null) {
        dummy1_ = null;
        onChanged();
      } else {
        dummy1_ = null;
        dummy1Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    public com.example.demo.protobuf.Dummy1P.Builder getDummy1Builder() {
      
      onChanged();
      return getDummy1FieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    public com.example.demo.protobuf.Dummy1POrBuilder getDummy1OrBuilder() {
      if (dummy1Builder_ != null) {
        return dummy1Builder_.getMessageOrBuilder();
      } else {
        return dummy1_ == null ?
            com.example.demo.protobuf.Dummy1P.getDefaultInstance() : dummy1_;
      }
    }
    /**
     * <code>.proto.Dummy1P dummy1 = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.Dummy1P, com.example.demo.protobuf.Dummy1P.Builder, com.example.demo.protobuf.Dummy1POrBuilder> 
        getDummy1FieldBuilder() {
      if (dummy1Builder_ == null) {
        dummy1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.demo.protobuf.Dummy1P, com.example.demo.protobuf.Dummy1P.Builder, com.example.demo.protobuf.Dummy1POrBuilder>(
                getDummy1(),
                getParentForChildren(),
                isClean());
        dummy1_ = null;
      }
      return dummy1Builder_;
    }

    private com.example.demo.protobuf.Dummy2P dummy2_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.Dummy2P, com.example.demo.protobuf.Dummy2P.Builder, com.example.demo.protobuf.Dummy2POrBuilder> dummy2Builder_;
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     * @return Whether the dummy2 field is set.
     */
    public boolean hasDummy2() {
      return dummy2Builder_ != null || dummy2_ != null;
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     * @return The dummy2.
     */
    public com.example.demo.protobuf.Dummy2P getDummy2() {
      if (dummy2Builder_ == null) {
        return dummy2_ == null ? com.example.demo.protobuf.Dummy2P.getDefaultInstance() : dummy2_;
      } else {
        return dummy2Builder_.getMessage();
      }
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    public Builder setDummy2(com.example.demo.protobuf.Dummy2P value) {
      if (dummy2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dummy2_ = value;
        onChanged();
      } else {
        dummy2Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    public Builder setDummy2(
        com.example.demo.protobuf.Dummy2P.Builder builderForValue) {
      if (dummy2Builder_ == null) {
        dummy2_ = builderForValue.build();
        onChanged();
      } else {
        dummy2Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    public Builder mergeDummy2(com.example.demo.protobuf.Dummy2P value) {
      if (dummy2Builder_ == null) {
        if (dummy2_ != null) {
          dummy2_ =
            com.example.demo.protobuf.Dummy2P.newBuilder(dummy2_).mergeFrom(value).buildPartial();
        } else {
          dummy2_ = value;
        }
        onChanged();
      } else {
        dummy2Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    public Builder clearDummy2() {
      if (dummy2Builder_ == null) {
        dummy2_ = null;
        onChanged();
      } else {
        dummy2_ = null;
        dummy2Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    public com.example.demo.protobuf.Dummy2P.Builder getDummy2Builder() {
      
      onChanged();
      return getDummy2FieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    public com.example.demo.protobuf.Dummy2POrBuilder getDummy2OrBuilder() {
      if (dummy2Builder_ != null) {
        return dummy2Builder_.getMessageOrBuilder();
      } else {
        return dummy2_ == null ?
            com.example.demo.protobuf.Dummy2P.getDefaultInstance() : dummy2_;
      }
    }
    /**
     * <code>.proto.Dummy2P dummy2 = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.protobuf.Dummy2P, com.example.demo.protobuf.Dummy2P.Builder, com.example.demo.protobuf.Dummy2POrBuilder> 
        getDummy2FieldBuilder() {
      if (dummy2Builder_ == null) {
        dummy2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.demo.protobuf.Dummy2P, com.example.demo.protobuf.Dummy2P.Builder, com.example.demo.protobuf.Dummy2POrBuilder>(
                getDummy2(),
                getParentForChildren(),
                isClean());
        dummy2_ = null;
      }
      return dummy2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.DistanceP)
  }

  // @@protoc_insertion_point(class_scope:proto.DistanceP)
  private static final com.example.demo.protobuf.DistanceP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.protobuf.DistanceP();
  }

  public static com.example.demo.protobuf.DistanceP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DistanceP>
      PARSER = new com.google.protobuf.AbstractParser<DistanceP>() {
    @java.lang.Override
    public DistanceP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DistanceP(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DistanceP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DistanceP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.protobuf.DistanceP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

